method = 'copy'
plugin_dirs = [
    '/home/carl/.wine/drive_c/Program Files/Steinberg/VstPlugins',
    '/home/carl/.wine/drive_c/Program Files (x86)/Steinberg/VstPlugins',
    '/home/carl/.vst',
]
no_verify = false
blacklist = []

[last_known_config]
wine_version = 'wine-7.8 (Staging)'
yabridge_host_hash = -4647292932629071920
