[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "mnist"
version = "0.1.0"
authors = [{ name = "Carl Thomé", email = "carlthome@gmail.com" }]
description = "A brief example of training a MNIST classifier with PyTorch Lightning"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fire>=0.5.0",
    "pytorch-lightning>=2.0.2",
    "torch>=2.0.1",
    "torchaudio>=2.0.2",
    "torchmetrics>=0.11.4",
    "torchvision>=0.15.0",
    "onnxruntime>=1.16.3",
    "onnx>=1.15.0",
    "gradio>=4.37.2",
    "fastapi>=0.111.0",
]

[project.optional-dependencies]
tests = ["pytest", "pytest-cov"]

[project.scripts]
mnist = "mnist.__main__:main"

[tool.pytest.ini_options]
pythonpath = ["src"]
