[package]
name = "rustler"
version = "0.1.0"
edition = "2024"

[dependencies]
crevice = "0.13.0"
ggez = "0.9.3"
rand = "0.9.1"

[[bin]]
name = "rustler"
path = "src/main.rs"

[package.metadata.ggez]
resources = ["resources"]
