on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - LICENSE
      - .gitignore
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - LICENSE
      - .gitignore

permissions:
  contents: read
  id-token: write

jobs:
  check:
    runs-on: ubuntu-latest
    concurrency:
      group: check-${{ github.ref }}
      cancel-in-progress: true
    outputs:
      packages: ${{ steps.detect.outputs.packages }}
      systems: ${{ steps.detect.outputs.systems }}
      homes: ${{ steps.detect.outputs.homes }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check --all-systems --no-build
      - id: detect
        run: .github/scripts/detect-builds.sh

  packages:
    needs: check
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.check.outputs.packages) }}
    runs-on: ${{ matrix.runs-on }}
    name: packages / ${{ matrix.name }} (${{ matrix.system }})
    concurrency:
      group: ${{ matrix.attr }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v17
        with:
          name: carlthome
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --print-build-logs .#${{ matrix.attr }}

  systems:
    needs: check
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.check.outputs.systems) }}
    runs-on: ${{ matrix.runs-on }}
    concurrency:
      group: ${{ matrix.attr }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-qemu-action@v3
        if: matrix.system == 'aarch64-linux'
        with:
          platforms: arm64
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-platforms = aarch64-linux
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v17
        with:
          name: carlthome
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --print-build-logs .#${{ matrix.attr }}

  homes:
    needs: check
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.check.outputs.homes) }}
    runs-on: ${{ matrix.runs-on }}
    concurrency:
      group: ${{ matrix.attr }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v17
        with:
          name: carlthome
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --print-build-logs .#${{ matrix.attr }}
