on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://koalaman/shellcheck-alpine:v0.8.0
        with:
          entrypoint: sh
          args: -c 'shellcheck --shell=bash --exclude=SC1090,SC2086 **/*.sh'
