on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://koalaman/shellcheck:v0.8.0 --shell=bash --exclude=SC1090,SC2086 **/*.sh
