on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/ping-home-app.yml"
      - "packages/ping-home/actions/deploy/**"
      - "packages/ping-home/app/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./packages/ping-home/actions/deploy
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          deploy_service_account: ${{ secrets.GOOGLE_CLOUD_DEPLOY_SERVICE_ACCOUNT }}
          google_cloud_region: ${{ secrets.GOOGLE_CLOUD_REGION }}
          image_tag: ${{ github.sha }}
