on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/ping-home-infra.yml"
      - "packages/ping-home/actions/infra/**"
      - "packages/ping-home/terraform/**"

jobs:
  plan-and-apply:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./packages/ping-home/actions/infra
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          terraform_service_account: ${{ secrets.GOOGLE_CLOUD_TERRAFORM_SERVICE_ACCOUNT }}
          terraform_state_bucket: ${{ secrets.TERRAFORM_STATE_BUCKET_NAME }}
          gh_app_id: ${{ vars.GH_APP_ID }}
          gh_app_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          google_cloud_project: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          google_cloud_region: ${{ secrets.GOOGLE_CLOUD_REGION }}
          github_repository: ${{ github.repository }}
