on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: carlthome/workflows/.github/workflows/nix.yaml@main
    with:
      cachix-auth-action: ${{ secrets.CACHIX_AUTH_ACTION }}
