on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: carlthome/workflows/.github/workflows/nix.yaml@main
    secrets:
      CACHIX_AUTH_ACTION: ${{ secrets.CACHIX_AUTH_ACTION }}
