on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update:
    uses: carlthome/workflows/.github/workflows/nix.yaml@main
    with:
      update: true
      cachix-cache: carlthome
    secrets:
      cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
